
"use client";
import ContactClient from "./contact-client";
import { Metadata } from 'next';

export const metadata:Metadata={
     title: "Contact Us | Kihondo",
  description: "Generated by create next app",

  }
export default function ContactPage() {
 
  return <ContactClient />;
}
