import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import banner from "@/public/contact.jpg"
export const metadata:Metadata={
      title: "Our Blog | Kihondo",
  description: "Generated by create next app",
}
export default function BlogPage() {
  const blogs = [
    {
      title: "Top 10 Safari Destinations in Tanzania",
      excerpt: "Discover the most breathtaking safari destinations across Tanzania including Serengeti, Ngorongoro, and Tarangire National Parks.",
      image: "/images/blog1.jpg",
      slug: "top-10-safari-destinations",
    },
    {
      title: "Exploring Zanzibar's Beaches and Culture",
      excerpt: "Relax on Zanzibar’s pristine beaches and dive into its rich culture and history. Tips for your perfect getaway.",
      image: "/images/blog2.jpg",
      slug: "exploring-zanzibar-beaches",
    },
    {
      title: "Climbing Mount Kilimanjaro: A Complete Guide",
      excerpt: "Everything you need to know to climb Africa’s highest peak, including preparation, routes, and safety tips.",
      image: "/images/blog3.jpg",
      slug: "climbing-kilimanjaro-guide",
    },
    {
      title: "Ngorongoro Crater Wildlife Adventure",
      excerpt: "Experience the incredible biodiversity of Ngorongoro Crater. Tips for safari photography and wildlife spotting.",
      image: "/images/blog4.jpg",
      slug: "ngorongoro-crater-adventure",
    },
  ];

  return (
    <main className="bg-zinc-50 dark:bg-black min-h-screen font-sans">

      {/* HERO BANNER */}
       <section className="relative h-[60vh] w-full bg-cover">
                          <Image
                            src={banner.src}
                            alt="About Explore Tanzania"
                            fill
                            className="object-cover"
                            priority
                          />
                          <div className="absolute inset-0 bg-black/50 flex items-center justify-center text-white py-16 ">
                           <h1 className="text-4xl font-bold">Tours & Safaris</h1>
             
                          </div>
              
                        </section>
      {/* BLOG LISTING */}
      <section className="py-16 px-4">
        <div className="max-w-7xl mx-auto grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
          {blogs.map((blog) => (
            <div key={blog.slug} className="bg-white dark:bg-zinc-800 shadow rounded-lg overflow-hidden hover:shadow-lg transition">
              <div className="relative h-48 w-full">
                <Image src={blog.image} alt={blog.title} fill className="object-cover" />
              </div>
              <div className="p-6">
                <h2 className="text-xl font-bold text-emerald-900 mb-2">{blog.title}</h2>
                <p className="text-gray-600 dark:text-gray-300 mb-4">{blog.excerpt}</p>
                <Link href={`/blog/${blog.slug}`} className=" font-semibold hover:underline bg-emerald-800 text-white px-3 py-2 rounded">
                  Read More
                </Link>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* PAGINATION (placeholder) */}
      <section className="py-8 text-center">
        <div className="flex justify-center gap-3">
          <button className="px-4 py-2 bg-emerald-600 text-white rounded hover:bg-emerald-700 transition">Prev</button>
          <button className="px-4 py-2 bg-emerald-600 text-white rounded hover:bg-emerald-700 transition">1</button>
          <button className="px-4 py-2 bg-emerald-600 text-white rounded hover:bg-emerald-700 transition">2</button>
          <button className="px-4 py-2 bg-emerald-600 text-white rounded hover:bg-emerald-700 transition">Next</button>
        </div>
      </section>

    </main>
  );
}
