import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Nav from "@/components/web/nav";
import { Suspense } from "react";
import Loading from "./loading";
import Footer from "@/components/web/footer";

import { SessionProvider } from "next-auth/react"
import WrapNav from "@/components/web/wrapLayout";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome To Kihondo | Home",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <WrapNav />
        

        {children}

        <Footer />
  <Toaster />
      </body>
    </html>
  );
}
